### ISSUE TITLE
JSX attributes with double quotes are being linted to use single quotes

### ISSUE THREAD

**Issue by carlows** [hashlabs/eslint-config-hashdard#2]
Whenever we use hashdard in react components the jsx attributes with double quotes are being linted to use single quotes. We want to use double quotes for jsx attributes an single quotes for every other code:

``` jsx
// bad
<a b='c' />

// good
<a b="c" />
```

[This rule](http://eslint.org/docs/rules/jsx-quotes) works for that but we should check it works as expected

**Comment by orlando** [comment]
@Carlows can you test this please?, if it works send a PR

**Comment by orlando** [comment]
Fixed by #3
